openapi: 3.1.0
info:
  title: Spendflix Auth API
  description: API for authentication (signup)
  version: 0.0.1

paths:
  /auth/signup:
    post:
      summary: User signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupRequest'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignupResponse'
        '400':
          description: Invalid request

components:
  schemas:
    SignupRequest:
      type: object
      required:
        - name
        - email
      properties:
        name:
          type: string
        email:
          type: string

    SignupResponse:
      type: object
      properties:
        message:
          type: string
        userId:
          type: string
