name: Danger Review

on:
  pull_request:
    branches:
      - main

jobs:
  danger_review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Danger
        run: npx danger ci --dangerfile=Dangerfile.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
