name: Test and Deploy Auth Service

on:
  push:
    branches:
      - main
    paths:
      - "services/auth/**"
  pull_request:
    branches:
      - main
    paths:
      - "services/auth/**"

jobs:
  services_auth_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Generate Types
        run: pnpm --filter ./services/auth generate:types

      - name: Run tests
        run: pnpm --filter ./services/auth test

  services_auth_deploy:
    if: github.event_name == 'push'
    needs: services_auth_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Generate Types
        run: pnpm --filter ./services/auth generate:types

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy Auth Service
        run: cd services/auth && pnpm sls deploy
